import Footer from './compnent/Footer'
import Header from './compnent/Header'
import NewsLetter from './compnent/NewsLetter'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Header/> {children}
       <NewsLetter/>
       <Footer/> </body>
    </html>
  )
}
